import type {
  User,
  Subject,
  StudyMaterial,
  LabEvent,
  Assessment,
  Question,
  Assignment,
  StudentResult,
  SemesterReport,
} from "@/types"

export const mockUsers: Record<string, User> = {
  student1: {
    id: "student1",
    email: "aditya.sharma@thapar.edu",
    name: "Aditya Sharma",
    rollNumber: "UE20CS012",
    branch: "CSE",
    role: "Student",
    profileImage: "/placeholder.svg?height=40&width=40",
  },
  teacher1: {
    id: "teacher1",
    email: "priya.verma@thapar.edu",
    name: "Prof. Priya Verma",
    branch: "CSE",
    role: "Teacher",
    profileImage: "/placeholder.svg?height=40&width=40",
  },
}

export const mockSubjects: Subject[] = [
  {
    id: "sub1",
    name: "Data Structures",
    code: "CS201",
    branch: "CSE",
    semester: 3,
    credits: 4,
    faculty: "Prof. Priya Verma",
  },
  {
    id: "sub2",
    name: "Web Development",
    code: "CS301",
    branch: "CSE",
    semester: 4,
    credits: 3,
    faculty: "Prof. Neha Singh",
  },
  {
    id: "sub3",
    name: "Database Management",
    code: "CS205",
    branch: "CSE",
    semester: 3,
    credits: 3,
    faculty: "Prof. Rajesh Patel",
  },
]

export const mockStudyMaterials: StudyMaterial[] = [
  {
    id: "mat1",
    subjectId: "sub1",
    title: "Arrays and Linked Lists",
    description: "Comprehensive guide on arrays and linked list implementations",
    type: "pdf",
    uploadedBy: "Prof. Amit Kumar",
    uploadedDate: "2024-11-15",
    fileUrl: "#",
    fileSize: "2.4 MB",
  },
  {
    id: "mat2",
    subjectId: "sub1",
    title: "Trees and Graphs - Video Lecture",
    description: "Complete video lecture on tree and graph data structures",
    type: "video",
    uploadedBy: "Prof. Amit Kumar",
    uploadedDate: "2024-11-10",
    fileUrl: "#",
    fileSize: "450 MB",
  },
  {
    id: "mat3",
    subjectId: "sub1",
    title: "Sorting Algorithms Implementation",
    description: "Detailed code examples for various sorting algorithms",
    type: "document",
    uploadedBy: "Prof. Amit Kumar",
    uploadedDate: "2024-11-08",
    fileUrl: "#",
    fileSize: "1.2 MB",
  },
  {
    id: "mat4",
    subjectId: "sub2",
    title: "React Fundamentals",
    description: "Introduction to React components and hooks",
    type: "presentation",
    uploadedBy: "Prof. Neha Singh",
    uploadedDate: "2024-11-12",
    fileUrl: "#",
    fileSize: "3.1 MB",
  },
  {
    id: "mat5",
    subjectId: "sub2",
    title: "CSS Layout Techniques",
    description: "Mastering Flexbox and Grid",
    type: "pdf",
    uploadedBy: "Prof. Neha Singh",
    uploadedDate: "2024-11-05",
    fileUrl: "#",
    fileSize: "1.8 MB",
  },
]

export const mockLabEvents: LabEvent[] = [
  {
    id: "lab1",
    title: "Data Structures Lab - Arrays",
    description: "Hands-on lab for array implementation and operations",
    date: "2024-12-15",
    time: "10:00 AM",
    duration: 120,
    branches: ["CSE"],
    eventType: "lab",
    location: "Lab-201",
    status: "scheduled",
    capacity: 30,
    enrolled: 28,
  },
  {
    id: "lab2",
    title: "Linked List Implementation Viva",
    description: "Viva examination for linked list concepts",
    date: "2024-12-18",
    time: "02:00 PM",
    duration: 60,
    branches: ["CSE"],
    eventType: "viva",
    location: "Lab-202",
    status: "scheduled",
    capacity: 15,
    enrolled: 14,
  },
  {
    id: "lab3",
    title: "Web Dev Project Presentation",
    description: "Students present their web development projects",
    date: "2024-12-20",
    time: "11:00 AM",
    duration: 180,
    branches: ["CSE"],
    eventType: "presentation",
    location: "Auditorium-A",
    status: "scheduled",
    capacity: 50,
    enrolled: 45,
  },
  {
    id: "lab4",
    title: "Database Lab - SQL Basics",
    description: "Introduction to SQL queries and database operations",
    date: "2024-12-10",
    time: "09:00 AM",
    duration: 90,
    branches: ["CSE"],
    eventType: "lab",
    location: "Lab-301",
    status: "completed",
    capacity: 25,
    enrolled: 23,
  },
]

export const mockQuestions: Question[] = [
  {
    id: "q1",
    assessmentId: "assess1",
    type: "mcq",
    questionText: "What is the time complexity of binary search?",
    order: 1,
    marks: 1,
    options: ["O(n)", "O(log n)", "O(n log n)", "O(n²)"],
    correctAnswer: 1,
  },
  {
    id: "q2",
    assessmentId: "assess1",
    type: "mcq",
    questionText: "Which data structure uses LIFO principle?",
    order: 2,
    marks: 1,
    options: ["Queue", "Stack", "Array", "Tree"],
    correctAnswer: 1,
  },
  {
    id: "q3",
    assessmentId: "assess1",
    type: "coding",
    questionText: "Write a function to find the sum of all elements in an array",
    order: 3,
    marks: 5,
    language: "javascript",
    boilerplateCode: `function arraySum(arr) {
  // Write your code here
}`,
    testCases: [
      { id: "tc1", input: "[1,2,3,4,5]", expectedOutput: "15", isHidden: false },
      { id: "tc2", input: "[10,20,30]", expectedOutput: "60", isHidden: true },
    ],
  },
]

export const mockAssessments: Assessment[] = [
  {
    id: "assess1",
    title: "Data Structures Quiz",
    subjectId: "sub1",
    description: "Quick assessment on basic data structures concepts",
    type: "mcq",
    duration: 30,
    totalMarks: 10,
    passcode: "1234",
    questions: mockQuestions.filter((q) => q.assessmentId === "assess1"),
    createdBy: "teacher1",
    createdDate: "2024-11-10",
    startTime: "2024-12-01T10:00:00",
    endTime: "2024-12-31T23:59:59",
    status: "published",
  },
  {
    id: "assess2",
    title: "Data Structures Final Exam",
    subjectId: "sub1",
    description: "Comprehensive exam including MCQs and coding problems",
    type: "mixed",
    duration: 120,
    totalMarks: 50,
    passcode: "5678",
    questions: mockQuestions,
    createdBy: "teacher1",
    createdDate: "2024-11-15",
    startTime: "2024-12-20T10:00:00",
    endTime: "2024-12-20T23:59:59",
    status: "published",
  },
]

export const mockAssignments: Assignment[] = [
  {
    id: "assign1",
    subjectId: "sub1",
    title: "Implement Binary Search Tree",
    description: "Create a complete BST implementation with insert, delete, and search operations",
    deadline: "2024-12-25",
    totalMarks: 20,
    groupSize: 1,
    attachments: ["bst-template.zip"],
    createdDate: "2024-11-15",
    createdBy: "teacher1",
  },
  {
    id: "assign2",
    subjectId: "sub1",
    title: "Graph Traversal Analysis",
    description: "Implement BFS and DFS with complexity analysis",
    deadline: "2024-12-28",
    totalMarks: 25,
    groupSize: 2,
    attachments: ["graph-template.zip"],
    createdDate: "2024-11-12",
    createdBy: "teacher1",
  },
  {
    id: "assign3",
    subjectId: "sub2",
    title: "Build a Todo Application",
    description: "Create a fully functional todo app using React",
    deadline: "2024-12-20",
    totalMarks: 30,
    groupSize: 1,
    attachments: [],
    createdDate: "2024-11-08",
    createdBy: "teacher1",
  },
]

export const mockStudentResults: StudentResult[] = [
  {
    id: "res1",
    studentId: "student1",
    assessmentId: "assess1",
    marksObtained: 9,
    totalMarks: 10,
    percentage: 90,
    status: "completed",
    submittedAt: "2024-12-05T10:45:00",
    feedback: "Excellent performance! Well done.",
  },
  {
    id: "res2",
    studentId: "student1",
    assessmentId: "assess2",
    marksObtained: 42,
    totalMarks: 50,
    percentage: 84,
    status: "completed",
    submittedAt: "2024-12-21T12:30:00",
    feedback: "Good work. Review topics on graph algorithms.",
  },
]

export const mockSemesterReports: SemesterReport[] = [
  {
    semester: 4,
    year: "2024",
    totalCredits: 20,
    enrolledCredits: 20,
    courses: [
      {
        courseId: "sub2",
        courseName: "Web Development",
        credits: 3,
        grade: "A",
        gradePoint: 9,
      },
      {
        courseId: "sub3",
        courseName: "Database Management",
        credits: 3,
        grade: "A-",
        gradePoint: 8.5,
      },
      {
        courseId: "sub1",
        courseName: "Data Structures",
        credits: 4,
        grade: "A",
        gradePoint: 9,
      },
    ],
    sgpa: 8.83,
    cgpa: 8.56,
  },
  {
    semester: 3,
    year: "2023",
    totalCredits: 22,
    enrolledCredits: 22,
    courses: [
      {
        courseId: "algo",
        courseName: "Algorithms",
        credits: 4,
        grade: "A",
        gradePoint: 9,
      },
      {
        courseId: "os",
        courseName: "Operating Systems",
        credits: 4,
        grade: "A-",
        gradePoint: 8.5,
      },
    ],
    sgpa: 8.45,
    cgpa: 8.35,
  },
]
